const OPEN_WEATHER_MAP_API_URL = "https://api.openweathermap.org/data/2.5/"
const BACKEND_API_URL = 'http://localhost:8080/api/';
const CURRENT_WEATHER_ICON = "01d";
const UNIT_OF_MEASUREMENT = "metric";
const PRIMARY_PLACE_ID = '763829';
const ALAN_STUDIO_KEY = "08ad7cc9b050e59ede0fd28653b9e0592e956eca572e1d8b807a3e2338fdd0dc/stage";
const OPEN_WEATHER_MAP_APP_ID =  "7aef87c2b6d81812c53c536b5a1d715c"
export default {
    OPEN_WEATHER_MAP_API_URL: OPEN_WEATHER_MAP_API_URL,
    OPEN_WEATHER_MAP_APP_ID: OPEN_WEATHER_MAP_APP_ID,
    BACKEND_API_URL: BACKEND_API_URL,
    CURRENT_WEATHER_ICON: CURRENT_WEATHER_ICON,
    UNIT_OF_MEASUREMENT: UNIT_OF_MEASUREMENT,
    PRIMARY_PLACE_ID: PRIMARY_PLACE_ID,
    ALAN_STUDIO_KEY: ALAN_STUDIO_KEY,
}
