const OPEN_WEATHER_MAP_API_URL = "https://api.openweathermap.org/data/2.5/"
const OPEN_WEATHER_MAP_APP_ID =  "7aef87c2b6d81812c53c536b5a1d715c"
const BACKEND_API_URL = 'http://localhost:8080/api/';
const CURRENT_WEATHER_ICON = "01d";
const PRIMARY_PLACE_ID = '';
export default {
    OPEN_WEATHER_MAP_API_URL: OPEN_WEATHER_MAP_API_URL,
    OPEN_WEATHER_MAP_APP_ID: OPEN_WEATHER_MAP_APP_ID,
    BACKEND_API_URL: BACKEND_API_URL,
    CURRENT_WEATHER_ICON: CURRENT_WEATHER_ICON,
    PRIMARY_PLACE_ID: PRIMARY_PLACE_ID,

}
